package br.jus.tream.saude.enumeration;

public enum TiposGuiaOdontologica {
	GUIA_ODONTO_PADRAO, REEMBOLSO_ODONTO_PADRAO, GUIA_ODONTO_IMPANTE, GUIA_ODONTO_EXAMES_PERIODICOS, REEMBOLSO_ODONTO_IMPLANTE;
}
